prowlarr:
  downloadClients:
    - name: qBittorrent
      implementationName: qBittorrent
      implementation: QBittorrent
      configContract: QBittorrentSettings
      fields:
        host: qbittorrent
        port: 8080
        username: admin
