services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: always
    env_file: .env
    ports:
      - 8096:8096
    volumes:
      - ./containers/jellyfin/config:/config
      - ./media/tvshows:/data/tvshows
      - ./media/movies:/data/movies

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    env_file: .env
    ports:
      - 7878:7878
    volumes:
      - ./containers/radarr:/config
      - ./media:/media:rw

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    env_file: .env
    ports:
      - 8989:8989
    volumes:
      - ./containers/sonarr:/config:rw
      - ./media:/media:rw

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    env_file: .env
    depends_on:
      - transmission
      - sonarr
      - radarr
    ports:
      - 9696:9696
    volumes:
      - ./containers/prowlarr:/config

  transmission:
    image: ghcr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    env_file: .env
    environment:
      - USER=admin
      - PASS=admin
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./containers/transmission:/config
      - ./media/downloads:/downloads
