services:
  plex:
    container_name: plex
    image: ghcr.io/linuxserver/plex:1.40.2.8395-c67dce28e-ls213
    env_file: .env
    dns: 8.8.8.8
    network_mode: host
    volumes:
      - ./containers/plex/config:/config:rw
      - ./containers/plex/transcode:/transcode:rw
      - ./media:/media:rw
    environment:
      - VERSION=latest

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr:5.4.6.8723-ls215
    env_file: .env
    dns: 8.8.8.8
    networks:
      - mediacenter
    ports:
      - 7878:7878
    volumes:
      - ./containers/radarr/config:/config
      - ./media:/media:rw

  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr:4.0.4.1491-ls236
    env_file: .env
    dns: 8.8.8.8
    networks:
      - mediacenter
    ports:
      - 8989:8989
    volumes:
      - ./containers/sonarr/config:/config:rw
      - ./media:/media:rw

  bazarr:
    container_name: bazarr
    image: ghcr.io/linuxserver/bazarr:v1.4.2-ls248
    env_file: .env
    dns: 8.8.8.8
    networks:
      - mediacenter
    ports:
      - 6767:6767
    volumes:
      - ./containers/bazarr/config:/config:rw
      - ./media:/media:rw

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/linuxserver/prowlarr:1.16.2.4435-ls66
    env_file: .env
    dns: 8.8.8.8
    networks:
      - mediacenter
    ports:
      - 9696:9696
    volumes:
      - ./containers/prowlarr/config:/config

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent:4.6.4-r1-ls326
    dns: 8.8.8.8
    env_file: .env
    environment:
      - WEBUI_PORT=8080
    networks:
      - mediacenter
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      - ./containers/qbittorrent/config:/config:rw
      - ./media/downloads:/downloads:rw

networks:
  mediacenter:
    ipam:
      driver: default
      config:
        - subnet: "172.16.1.0/24"
