version: '3'

services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    env_file: .env
    network_mode: host
    environment:
      - VERSION=latest
    volumes:
      - ./plex/config:/config:rw
      - ./plex/transcode:/transcode:rw
      - ./media:/media:rw

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    env_file: .env
    dns: 8.8.8.8
    volumes:
      - ./radarr:/config
      - ./media:/media:rw
    ports:
      - 7878:7878

  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    env_file: .env
    dns: 8.8.8.8
    ports:
      - 8989:8989
    volumes:
      - ./sonarr:/config:rw
      - ./media:/media:rw

  bazarr:
    container_name: bazarr
    image: ghcr.io/linuxserver/bazarr
    env_file: .env
    dns: 8.8.8.8
    ports:
      - 6767:6767
    volumes:
      - ./bazarr:/config:rw
      - ./media:/media:rw

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    env_file: .env
    dns: 8.8.8.8
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent:libtorrentv1-release-4.6.4_v1.2.19-ls22@sha256:5c8f04ab0c493682bb961dfe51e07e10a6f1527e34fe5619498b2a9087713423
    dns: 8.8.8.8
    env_file: .env
    environment:
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config:rw
      - ./media/downloads:/downloads:rw
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
