services:
  plex:
    container_name: plex
    image: ghcr.io/linuxserver/plex:1.40.2.8395-c67dce28e-ls213
    env_file: .env
    dns: 8.8.8.8
    network_mode: host
    volumes:
      - ./containers/plex/config:/config:rw
      - ./containers/plex/transcode:/transcode:rw
      - ./media:/media:rw
    environment:
      - VERSION=latest

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr:5.4.6.8723-ls215
    env_file: .env
    dns: 8.8.8.8
    ports:
      - 7878:7878
    volumes:
      - ./containers/radarr:/config
      - ./media:/media:rw

  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr:4.0.4.1491-ls236
    env_file: .env
    dns: 8.8.8.8
    ports:
      - 8989:8989
    volumes:
      - ./containers/sonarr:/config:rw
      - ./media:/media:rw

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/linuxserver/prowlarr:1.16.2.4435-ls66
    env_file: .env
    dns: 8.8.8.8
    depends_on:
      - transmission
      - sonarr
      - radarr
    ports:
      - 9696:9696
    volumes:
      - ./containers/prowlarr:/config

  transmission:
    container_name: transmission
    image: ghcr.io/linuxserver/transmission:4.0.5
    env_file: .env
    environment:
      - USER=admin
      - PASS=admin
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./containers/transmission:/config
      - ./media/downloads:/downloads
