version: '3'

services:
  plex:
    container_name: plex
    image: ghcr.io/linuxserver/plex
    env_file: .env
    dns: 8.8.8.8
    network_mode: host
    volumes:
      - ./plex/config:/config:rw
      - ./plex/transcode:/transcode:rw
      - ./media:/media:rw
    environment:
      - VERSION=latest

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    env_file: .env
    dns: 8.8.8.8
    ports:
      - 7878:7878
    volumes:
      - ./radarr:/config
      - ./media:/media:rw

  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    env_file: .env
    dns: 8.8.8.8
    ports:
      - 8989:8989
    volumes:
      - ./sonarr:/config:rw
      - ./media:/media:rw

  bazarr:
    container_name: bazarr
    image: ghcr.io/linuxserver/bazarr
    env_file: .env
    dns: 8.8.8.8
    ports:
      - 6767:6767
    volumes:
      - ./bazarr:/config:rw
      - ./media:/media:rw

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/linuxserver/prowlarr
    env_file: .env
    dns: 8.8.8.8
    ports:
      - 9696:9696
    volumes:
      - ./prowlarr:/config

  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent
    dns: 8.8.8.8
    env_file: .env
    environment:
      - WEBUI_PORT=8080
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      - ./qbittorrent:/config:rw
      - ./media/downloads:/downloads:rw
